### ISSUE TITLE
LoadLibrary problem on startup (Windows 8 64bit)

### ISSUE THREAD

**Issue by nonozelmar** [matpow2/cuwo#113]
I download the rebuilt cuwo and when i stat the run.bat , it say : 
"A:\t?lechargement\cuwo-e45afdd\dist\bin\serveur.exe
LoadLibrary<python11> failedLe module spùcifiù est introuvable.
2A:\t?lechargement\cuwo-ea45afdd\dist\bin\PYTHON27.dll
A:\t?lechargement\cuwo-ea45fdd\dist\pause"

**Comment by matpow2** [comment]
Closing, reopen if the problem persists
