### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by saber00** [matpow2/cuwo#164]
When I do /teleport 
http://pastebin.com/sPVBPPEy

/heal
http://pastebin.com/dhaz650p

Also, when I enable the King of the Hill or Team Death Match Script:
http://pastebin.com/6UVnbz3Y

**Comment by J-Igor** [comment]
The same error with /heal
http://pastebin.com/z2BzLXVe
and /teleport
http://pastebin.com/MbpWB5Qg
on Ubuntu 14.04

**Comment by J-Igor** [comment]
Error in scripts/commands.py:146
There must be 
```python
player.entity.damage(-int(hp))
```
instead of
```python
player.damage(-int(hp))
```

**Comment by matpow2** [comment]
Fixed in trunk
