### ISSUE TITLE
tgen entity issue with multiple clients connected

### ISSUE THREAD

**Issue by UserXXX** [matpow2/cuwo#169]
If you log in with one client, go to a place where entities are, wait for the generation ofthe current chunk and then log in with another client and go to the same chunk the first client will display NPCs correct but the second sees none of them. Also if i.e. a door is opened by a client and a second client logs in after that he will see the door as closed. If he tries to open the door it will show the close animation and from then on work as intended.
![tgen entity bug](https://cloud.githubusercontent.com/assets/7149263/6200581/4630babe-b47f-11e4-8413-11f1bad0013a.PNG)
In the screenshot "Test 3" was logged in after "Test 2".
It seems like the chunks entity data is only transferred once after it got generated.

**Comment by matpow2** [comment]
That's weird, I was sure I had tested this. I'll take your word for it and put this as an issue though.
