### ISSUE TITLE
Unable to build cuwo on windows

### ISSUE THREAD

**Issue by UserXXX** [matpow2/cuwo#172]
I followed the steps given here: https://github.com/matpow2/cuwo/wiki/WindowsSource
Also I copied all necessary files (Server.exe with correct MD5 and data1/4.db) to the "data" directory.
When I run build.bat it says:
PS F:\Development\Python\cuwo-source\cuwo-master> .\build.bat

F:\Development\Python\cuwo-source\cuwo-master>C:\Windows\py.exe -3 setup.py build_ext --inplace
Using SSE2 optimizations
Compiling ./terraingen/pydasm/pydasm.pyx because it changed.
Compiling ./cuwo/tgen.pyx because it changed.
Compiling ./cuwo/bytes.pyx because it changed.
Compiling ./cuwo/entity.pyx because it changed.
Cythonizing ./cuwo/bytes.pyx
Cythonizing ./cuwo/entity.pyx
Cythonizing ./cuwo/tgen.pyx
Cythonizing ./terraingen/pydasm/pydasm.pyx
running build_ext
building 'terraingen.pydasm' extension
creating build
creating build\temp.win32-3.4
creating build\temp.win32-3.4\Release
creating build\temp.win32-3.4\Release\terraingen
creating build\temp.win32-3.4\Release\terraingen\pydasm
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS -DENABLE_SSE2 "-IC:\Program Files (x86)\Python34\include" "-IC:\Program Files (x86)\Python34\include" /Tc./
terraingen/pydasm/pydasm.c /Fobuild\temp.win32-3.4\Release\./terraingen/pydasm/pydasm.obj
pydasm.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS -DENABLE_SSE2 "-IC:\Program Files (x86)\Python34\include" "-IC:\Program Files (x86)\Python34\include" /Tc./
terraingen/pydasm/libdasm.c /Fobuild\temp.win32-3.4\Release\./terraingen/pydasm/libdasm.obj
libdasm.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files (x86)\Python34\libs" "/LIBPATH:C:\Program Files (x86)\Python34\PCbuild" /EXPORT:PyInit_pydasm build\temp.win32-3
.4\Release\./terraingen/pydasm/pydasm.obj build\temp.win32-3.4\Release\./terraingen/pydasm/libdasm.obj /OUT:F:\Development\Python\cuwo-source\cuwo-master\terraingen\pydasm.pyd /IMPLIB:build\temp.win32-3.4\Release\./terraingen/pydasm\pyd
asm.lib /MANIFESTFILE:build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.pyd.manifest
   Bibliothek "build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.lib" und Objekt "build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.exp" werden erstellt. (*1, see below)
Generating sources for tgen...
Image base: 400000
Conversion skipped 549AD0:
Handler skipped: [0x549e1d][e8] call 0xffec91c3
Conversion skipped 54A738:
Not implemented: [0x54a9fa][cd] int 0x29
Conversion skipped 4311E0:
Not implemented: [0x43123a][9d] setnl dl
Conversion skipped 4C7B70:
Not implemented: [0x4c7bcd][9d] setnl dl
Conversion skipped 42A7D0:
Not implemented: [0x42a829][9d] setnl dl
Conversion skipped 41CC60:
Not implemented: [0x41ccb6][2e] ucomiss xmm0,[edi+0x130]
Instruction stats: [('mov', 49577), ('push', 33790), ('call', 19771), ('lea', 16087), ('add', 6285), ('cmp', 4285), ('pop', 3223), ('movss', 2820), ('sub', 2256), ('test', 2113)]
Generated 835 source files.
Building static tgen library (this may take a while)
[... build progress ...]
LINK : fatal error LNK1104: Datei "lib\tgen.lib" kann nicht geöffnet werden. (*2)
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\lib.exe' failed with exit status 1104

run_server.bat gives:
PS F:\Development\Python\cuwo-source\cuwo-master> .\run_server.bat

F:\Development\Python\cuwo-source\cuwo-master>C:\Windows\py.exe -3 -m cuwo.server
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Development\Python\cuwo-source\cuwo-master\cuwo\server.py", line 18, in <module>
    from cuwo import packet as packets
  File "F:\Development\Python\cuwo-source\cuwo-master\cuwo\packet.py", line 24, in <module>
    from cuwo.entity import (EntityData, ItemData, read_masked_data,
ImportError: No module named 'cuwo.entity'

Translations:
(*1): Creating library "build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.lib" and object "build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.exp"
(*2): Unable to open file "lib\tgen.lib".

It seems that "lib\tgen.lib" is not created as I can't find it anywhere within the cuwo-master directory.
I'm running on Windows 7 64 bit using Python 3.4.1 32 bit with Cython 0.22 for Python 3.4 and Microsoft Visual Studio 2010 C++ Express (also 32 bit).

**Comment by matpow2** [comment]
Try and comment out line 202 and 230 in setup.py, then rebuild.
It's probably not building tgen.lib due to some error, so check out the output from the compiler.

**Comment by UserXXX** [comment]
This is the output I get:
F:\Development\Python\cuwo-source\cuwo-master>C:\Windows\py.exe -3 setup.py build_ext --inplace
Using SSE2 optimizations
Compiling ./terraingen/pydasm/pydasm.pyx because it changed.
Compiling ./cuwo/tgen.pyx because it changed.
Compiling ./cuwo/bytes.pyx because it changed.
Compiling ./cuwo/entity.pyx because it changed.
Cythonizing ./cuwo/bytes.pyx
Cythonizing ./cuwo/entity.pyx
Cythonizing ./cuwo/tgen.pyx
Cythonizing ./terraingen/pydasm/pydasm.pyx
running build_ext
building 'terraingen.pydasm' extension
creating build
creating build\temp.win32-3.4
creating build\temp.win32-3.4\Release
creating build\temp.win32-3.4\Release\terraingen
creating build\temp.win32-3.4\Release\terraingen\pydasm
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS -DENABLE_SSE2 "-IC:\Program Files (x86)\Python34\include" "-IC:\Program Files (x86)\Python34\include" /Tc./
terraingen/pydasm/pydasm.c /Fobuild\temp.win32-3.4\Release\./terraingen/pydasm/pydasm.obj
pydasm.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -D_CRT_SECURE_NO_WARNINGS -DENABLE_SSE2 "-IC:\Program Files (x86)\Python34\include" "-IC:\Program Files (x86)\Python34\include" /Tc./
terraingen/pydasm/libdasm.c /Fobuild\temp.win32-3.4\Release\./terraingen/pydasm/libdasm.obj
libdasm.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files (x86)\Python34\libs" "/LIBPATH:C:\Program Files (x86)\Python34\PCbuild" /EXPORT:PyInit_pydasm build\temp.win32-3
.4\Release\./terraingen/pydasm/pydasm.obj build\temp.win32-3.4\Release\./terraingen/pydasm/libdasm.obj /OUT:F:\Development\Python\cuwo-source\cuwo-master\terraingen\pydasm.pyd /IMPLIB:build\temp.win32-3.4\Release\./terraingen/pydasm\pyd
asm.lib /MANIFESTFILE:build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.pyd.manifest
   Bibliothek "build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.lib" und Objekt "build\temp.win32-3.4\Release\./terraingen/pydasm\pydasm.exp" werden erstellt.
Generating sources for tgen...
Image base: 400000
Conversion skipped 549AD0:
Handler skipped: [0x549e1d][e8] call 0xffec91c3
Conversion skipped 54A738:
Not implemented: [0x54a9fa][cd] int 0x29
Conversion skipped 4311E0:
Not implemented: [0x43123a][9d] setnl dl
Conversion skipped 4C7B70:
Not implemented: [0x4c7bcd][9d] setnl dl
Conversion skipped 42A7D0:
Not implemented: [0x42a829][9d] setnl dl
Conversion skipped 41CC60:
Not implemented: [0x41ccb6][2e] ucomiss xmm0,[edi+0x130]
Instruction stats: [('mov', 49577), ('push', 33790), ('call', 19771), ('lea', 16087), ('add', 6285), ('cmp', 4285), ('pop', 3223), ('movss', 2820), ('sub', 2256), ('test', 2113)]
Generated 835 source files.
Building static tgen library (this may take a while)
[... progress ...]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\lib.exe @build\temp.win32-3.4\Release\link.rsp /NOLOGO /OUT:lib\tgen.lib
LINK : fatal error LNK1104: Datei "lib\tgen.lib" kann nicht geöffnet werden.
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\lib.exe' failed with exit status 1104

**Comment by matpow2** [comment]
Are you missing a "lib" dir in the root folder?

**Comment by UserXXX** [comment]
Yes, I am.

**Comment by matpow2** [comment]
Create it and rerun.

**Comment by UserXXX** [comment]
It worked, thank you. Maybe you can add a note to the wiki article ;)
