### ISSUE TITLE
PVE-SEVER with..

### ISSUE THREAD

**Issue by Xxendor** [matpow2/cuwo#173]
hi i want to make a private server to play with friends as PVE but we want commands and admins ca someone please make one for me i cant understand the files,and i was trying to make one but there are no MOBS or creatures like PVP and we could not even do DMG to players was useless, we are trying to play CW as normaly but with Admins

**Comment by TheReverend403** [comment]
Cuwo does not currently support entities. If you want a PVE server, the
only way is with the official Cube World server software.

**Comment by Xxendor** [comment]
is there any way to put admins or something like that?

**Comment by TheReverend403** [comment]
Not that I know of

**Comment by Xxendor** [comment]
is ZIRCON.TK with CUWO?

**Comment by Kainzo** [comment]
Probably not, but ask them.

**Comment by Xxendor** [comment]
where ; -;

**Comment by matpow2** [comment]
Closing
