### ISSUE TITLE
Not adding server to serverlist on CUWO.org

### ISSUE THREAD

**Issue by Kainzo** [matpow2/cuwo#175]
I can say for 100% that the ports are forwarded correctly, the server isnt showing up even after an hour of being online. "cwpvp.com"

-----------------------------------------------------------------------------------
# Server hostname to connect to
server = 'mp2.dk'

# Server port to connect to
port = 12364

# Hostname to use for the list. Set to empty for current IP.
hostname = None

**Comment by matpow2** [comment]
Hnm, let me look into this. Our server may have restarted.

**Comment by matpow2** [comment]
What IP are you requesting this from?
Also, are you getting 'Received response from master server'?

**Comment by Kainzo** [comment]
Sorry about that @matpow2 Matpow2
got snowed in, the IP is from "192.99.148.33"

This is a pretty fresh installation too.
