### ISSUE TITLE
Attempting to mess around with recompilation converter.py

### ISSUE THREAD

**Issue by fatrolls** [matpow2/cuwo#176]
I'm trying to learn about the method of x86 recomplication instead of cpu emulating every instruction.

I can't seem to run the converter.py it crashes.

C:\terraingen>Python converter.py "C:\terraingen\server.exe"
Image base: 400000
Not writing data header for rdata_section.h
Not writing data header for data_section.h
Traceback (most recent call last):
  File "converter.py", line 2362, in <module>
    main()
  File "converter.py", line 2359, in main
    convert(args.file)
  File "converter.py", line 2348, in convert
    converter = Converter(filename)
  File "converter.py", line 2048, in __init__
    subs = self.get_subs(address)
  File "converter.py", line 2216, in get_subs
    sub = Subroutine(self, address)
  File "converter.py", line 646, in __init__
    instruction = Instruction(raw_instruction, address, converter)
  File "converter.py", line 488, in __init__
    self.eflags_affected = i.eflags_affected;
AttributeError: class Instruction has no attribute 'eflags_affected'
`

in Python script it's this line
`
affected = eflags_affected.get(self.mnemonic, i.eflags_affected)
`

The __slots__ has the attribute so why it says no attribute error?

`
    __slots__ = ['converter', 'address', 'has_reloc', 'length', 'type', 'mode',
                 'opcode', 'modrm', 'sib', 'extindex', 'fpuindex', 'dispbytes',
                 'immbytes', 'sectionbytes', 'flags', 'op1', 'op2', 'op3',
                 'prefix', 'eflags_affected', 'eflags_used',
                 'eflags_dependency', 'disasm', 'mnemonic',
                 'condition_value']
`

**Comment by matpow2** [comment]
Did you run with the right Server.exe version? It should really just work out of the box.

**Comment by fatrolls** [comment]
yes i did.. the md5 hash matched up.. the first Server.exe didn't work the next one worked I used the one from http://cuwo.org/Server.exe it's just this faulty one line in the python script I can't figure out how to fix it either.. i looked all over stackoverflow questions and can't figure it out python isn't my thing I want to port this script over to .NET later.

**Comment by fatrolls** [comment]
I figured out the problem I just don't know how to fix it..

here is where it screws up
```
Address   Hex dump          Command
00412DD6      85FF          TEST EDI,EDI
00412DD8      79 04         JNS SHORT 00412DDE
00412DDA      33FF          XOR EDI,EDI
00412DDC      EB 02         JMP SHORT 00412DE0
00412DDE      75 28         JNZ SHORT 00412E08
```

the comparer TEST has dependees on JNS but should it also be dependees on JNZ aswell right?

What happens is the TEST instruction goes to JNS then the JNS may go to JNZ and JNZ has no dependees back to TEST?  which means it has no condition_value is set which throws the Not implemented Exception

**Comment by fatrolls** [comment]
There is no way this would work out of the box I had to add many new instructions such as `on_xorpd` which is same as `on_xorps` i believe, `on_ucomiss`, `on_ucomisd` were missing I have no idea how to implement them `on_setnl` was missing I rerouted it like all those `on_setxx` to `on_setcc` have to implement `on_sqrtps`, `on_lahf` a few others too.. but yeah it generated 843 files in the gensrc folder atm I believe the converter script you released is outdated no?

**Comment by matpow2** [comment]
Just to check, what revision are you on?

**Comment by fatrolls** [comment]
no idea didn't check when i downloaded it as a zip file, its over 1 year old now and was like that i assume when i downloaded it 12 or so days ago.

It might be due to my fixes i applied to the script it started going into functions which you never translated so those instructions you have never met

**Comment by matpow2** [comment]
Get the latest revision, some things probably changed since you retrieved the ZIP.

Even though the converter hits some unimplemented instructions, those areas of the executable are never met anyway, so you can ignore those.
