### ISSUE TITLE
Missing VC redist files on standalone Windows build

### ISSUE THREAD

**Issue by WildKarrade** [matpow2/cuwo#179]
I just tried downloading the latest build from the wiki, unzipping and running the batch file and it fails with no MSVCR100.dll found error even though other apps that need it work fine. And I tried running as admin as well, do I need to compile the latest version?

**Comment by matpow2** [comment]
Ah, the dreadful DLL hell. Basically, you need to install the VC++ 2010 runtime libraries:
https://www.microsoft.com/en-us/download/details.aspx?id=5555

The binaries are really old by now, so you are better of building from source.

**Comment by cindylo** [comment]
Very weird then I do have that redist installed since killing floor 2 server requires it. And i reinstalled to make sure I wasn't missing anything and it still did it.

I did try and compile and I got an issue with that as well with this command. 
python setup.py build_ext --inplace

Using SSE2 optimizations
running build_ext
building 'terraingen.pydasm' extension
error: [WinError 2] The system cannot find the file specified

**Comment by maki-chan** [comment]
Do you use the Python >= 3.3? Even if it is installed, there could be a Python 2.X installation. Run `python --version` to see what version you have. Maybe you need to call it via `python3` or something similar.

**Comment by cindylo** [comment]
3.5 to be exact

**Comment by maki-chan** [comment]
Then you should update the README.md. It still states

> Make sure you have Python >= 3.3 and cython installed on your machine, along with native compilers.
>
> On Python versions below 3.4, you will need asyncio installed.

**Comment by TheReverend403** [comment]
There's nothing wrong with the readme, it's been accurate since the
initial port to Python 3.

**Comment by maki-chan** [comment]
Ah, sry, I confused something here ;)

I confused cindylo with the developer (don't know why), sry

**Comment by matpow2** [comment]
Fixed in 166d2f7.

**Comment by matpow2** [comment]
Still missing e.g. MSVCP140.dll and other UCRT DLLs, need to investigate.

**Comment by matpow2** [comment]
Actually fixed in fda444e.
