### ISSUE TITLE
Error when building cuwo on Debian: "No module named 'numpy'"

### ISSUE THREAD

**Issue by SinusStudios** [matpow2/cuwo#198]
Followed this guide, method 2 because 1 is not working for me: https://github.com/matpow2/cuwo/wiki/BuildSource

No errors up until building cuwo using "python3.6 setup-py build-ext --inplace", output:
`Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'`
(Run as normal user inside /home/<user>/cuwo/cuwo-master/)

**Comment by matpow2** [comment]
Why didn't method 2 work for you?
You can simply install numpy for python3.6, but I'd like to fix method 2 if possible.

**Comment by SinusStudios** [comment]
(I think you accidentially mixed up Methods 1 and 2, i attempted Method 1 (automated, bootstrap.sh) but it failed and then i tried Method 1 (manual) which resulted in the error above.)
Okay so here's what i get when running `curl -L http://cuwo.org/bootstrap.php | bash` in the third step of Method 1 (bootstrap.sh):
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106  100   106    0     0    106      0  0:00:01 --:--:--  0:00:01  1341
: No such file or directory
bash: line 2: syntax error near unexpected token `"Location: https://raw.githubusercontent.com/matpow2/cuwo/master/bootstrap.sh"'
'ash: line 2: `header("Location: https://raw.githubusercontent.com/matpow2/cuwo/master/bootstrap.sh");`
Installation of the packages was successful and i'm running the command as a normal user inside an empty directory /cuwo/. Prefixing `sudo` doesn't change the output.

**Comment by yakuuz** [comment]
## Method 1.5 (clone + bootstrap manuel)
1. First, install the prerequisites for Python 3.6 and git.
 * Ubuntu/Debian:
 `sudo apt-get install -y git build-essential libsqlite3-dev libssl-dev libbz2-dev libreadline-dev`
2. Create a new directory (e.g. `~/cuwo`) and `cd` into it.
3. Run `sudo git clone https://github.com/matpow2/cuwo.git && cd cuwo`
4. Remove line 1-5 from bootstrap.sh and Run it `./bootstrap.sh`
5. Upload data files or login (6.) to download it.
6. Run `sh run_server.sh`

this works for me 👍 ^.^

**Comment by SinusStudios** [comment]
my bootstrap.sh after removing lines 1-5: 

> 
# create run_pyenv.sh
echo '#!/usr/bin/env bash' > run_pyenv.sh
echo 'export PYENV_ROOT=${HOME}/.pyenv' >> run_pyenv.sh
echo 'if [ -d "${PYENV_ROOT}" ]; then' >> run_pyenv.sh
echo '  export PATH="${PYENV_ROOT}/bin:${PATH}"' >> run_pyenv.sh
echo '  eval "$(pyenv init -)"' >> run_pyenv.sh
echo 'fi' >> run_pyenv.sh

# create update.sh
echo '#!/usr/bin/env bash' > update.sh
echo 'cd "$(dirname "$0")"' >> update.sh
echo '. ./run_pyenv.sh' >> update.sh
echo 'git pull' >> update.sh
echo 'python setup.py build_ext --inplace' >> update.sh

. ./run_pyenv.sh

pyenv update
pyenv install 3.6.1 --skip-existing
pyenv local 3.6.1
pip install -r requirements.txt
python setup.py build_ext --inplace

chmod +x run_server.sh
chmod +x update.sh
> 
Running either `sudo ./bootstrap.sh` or `./bootstrap.sh` results in: 
>
./bootstrap.sh: 19: ./bootstrap.sh: pyenv: not found
./bootstrap.sh: 20: ./bootstrap.sh: pyenv: not found
./bootstrap.sh: 21: ./bootstrap.sh: pyenv: not found
Collecting Cython (from -r requirements.txt (line 1))
  Downloading Cython-0.27.2-cp27-cp27mu-manylinux1_x86_64.whl (3.0MB)
    100% |################################| 3.0MB 381kB/s
Collecting pyrr (from -r requirements.txt (line 2))
  Downloading pyrr-0.9.2-py2.py3-none-any.whl (65kB)
    100% |################################| 71kB 9.3MB/s
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from pyrr->-r requirements.txt (line 2))
Collecting multipledispatch (from pyrr->-r requirements.txt (line 2))
  Downloading multipledispatch-0.4.9-py2.py3-none-any.whl
Installing collected packages: Cython, multipledispatch, pyrr
Successfully installed Cython-0.27.2 multipledispatch-0.4.9 pyrr-0.9.2
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    from cuwo.download import download_dependencies
  File "/home/roman/cuwo/cuwo/cuwo/download.py", line 95
    def download_prompt(*files, email=None, password=None):
                                    ^
SyntaxError: invalid syntax
> 
Also i don't understand what you mean with Step 5
Thanks for your efforts on helping so far =)

**Comment by matpow2** [comment]
Can you check method 1 again? https://cuwo.org/bootstrap.sh isn't working right now, so I updated the URL.
