### ISSUE TITLE
Spawnkilling

### ISSUE THREAD

**Issue by CheckTheDome** [matpow2/cuwo#219]
Hey there,

firstly your work here is highly appreciated, it's amazing that there are still people working on CubeWorld Servers. 
Anyway i got some kind of Bug when trying to play on a private server. At first everything seems fine when starting it but after a few minutes or so i get teleported to the edge of the map and i keep dying to a lvl 1 Cotton Plant apparently. I just wanted to know if that has actually something to do with cuwo or if it's caused by playing the cracked version of the game (discovered this amazing game too late).

Anyway thanks in advance for every response :)

**Comment by matpow2** [comment]
Should be fixed in cb29782.
